### ISSUE TITLE
Change planet states based on distance from star

### ISSUE THREAD

**Issue by nstgeorge** [nstgeorge/VEKTA#42]
Stars should now have temperature values (which change the color of the star). When a planet is close to a star, it should effect its habitability and any civilizations living on the planet.

If a planet approaches fairly slowly, it should experience slower changes that the civilization can adapt to. Otherwise, it should rapidly increase in temperature and the civilization should die out, leaving it abandoned. If it re-enters a habitable zone, life should have a chance to start again.

**Comment by rvanasa** [comment]
Tips for working on this issue:

- All space objects have built-in temperature/heat which can be accessed via `SpaceObject::getTemperature()`, `SpaceObject::getSpecificHeat()`, etc.
- You can access the settlements on a `TerrestrialPlanet` via `planet.getLandingSite().getTerrain().getSettlements()`.
- Planets are considered habitable iff they have the `"Habitable"` terrain attribute. 
- Note that swapping out `Terrain` objects will cause all sorts of memory leaks, so ideally we want to create a new `AdaptiveTerrain` subclass that will periodically update settlements/attributes. I just added a `Terrain::onOrbit(SpaceObject orbitObject)`, so terrain changes should happen whenever this method is called.

**Comment by nstgeorge** [comment]
Done by class-merge.
