### ISSUE TITLE
Add re-entry effects when passing or landing on a planet with atmosphere

### ISSUE THREAD

**Issue by nstgeorge** [nstgeorge/VEKTA#43]

**Comment by StGerGer** [comment]
From @rvanasa: To implement this cleanly, perhaps we could add a `boolean isAtmospheric()` accessor to Planet (and maybe even `float getAtmosphereDistance()`). From there, we could have a particle emitter on ModularShip which periodically updates the emission properties based on the position in the atmosphere.

**Comment by nstgeorge** [comment]
Done in class-merge.
