### ISSUE TITLE
Fix performance issues on certain machines

### ISSUE THREAD

**Issue by nstgeorge** [nstgeorge/VEKTA#59]
As of right now, my desktop is the only computer tested that's having significant performance issues. Here are my quick specs (even though I'll be the one working on this, might as well have it here for future reference):

Windows 10 Pro 2004 (Build 19041.450)
Ryzen 5 3600
RTX 2060
16 GB DDR4 RAM

When the game starts, the frame rate rapidly drops from 60 fps to around 10-12 within seconds. The culprit appears to be hiding in the object drawing portion of the update loop.

**Comment by StGerGer** [comment]
I've narrowed it down to something in the `drawTrail` function. Not quite sure yet what it is, I'll look into it more in the morning.

**Comment by nstgeorge** [comment]
This was a local issue, problem has been solved.
