### ISSUE TITLE
Most menus are wonky

### ISSUE THREAD

**Issue by rvanasa** [nstgeorge/VEKTA#79]
### Steps to Reproduce
1. Fullscreen, 1920x1080, pixel density 1
2. Press "E" and try to scroll through the menu.

### Actual Results
The cursor moves off the screen. 

### Expected Results
The buttons should be closer together and are intended to smoothly scroll in the opposite direction the cursor. 

### Other Notes
Menu buttons are generally rendering incorrectly. I'm guessing that this is related to the new `ScrollableContainer` logic, which might have some edge cases. Because the menus are important for testing and development, fixing this would be a top priority.

**Comment by nstgeorge** [comment]
I changed the number of menu items before a menu becomes scrollable. Likely reverting this change will fix some of these issues.
