### ISSUE TITLE
Planet temperatures have unexpected values

### ISSUE THREAD

**Issue by rvanasa** [nstgeorge/VEKTA#80]
### Steps to Reproduce
1. Open the debug menu by pressing tilde [ ` ].
2. Select "Give Knowledge".
3. Scroll through planet temperatures.

### Actual Results
All terrestrial planets usually have star-like temperatures (2000-5000 C). 

### Expected Results
Most temperatures should be in a range closer to -200 to 200 C. 

### Other Notes
Because this is blocking for #66, I can just rewrite the temperature logic but just wanted to drop this bug report in case it's easily fixable.

**Comment by rvanasa** [comment]
For documentation purposes, I'll write that the temperature generation logic appears to work, so the star class distribution and planet distances are the main issue.

**Comment by nstgeorge** [comment]
Aren't temps in Kelvin, not C? If it's showing up as °C we need to fix labelling as well.

**Comment by nstgeorge** [comment]
Not that that makes the temps any more realistic...

I'm fairly certain the temperature code is good and it's the system generation that's causing the super high temps. It's possible I made some assumption about each planet that doesn't hold. I'll have to take another look at the equation I used.

**Comment by rvanasa** [comment]
Yeah, the logic seems sound, so it could be something to do with rounding the very tiny/large numbers associated with the Stefan-Boltzmann constant. I'll keep trying things. 

Everything's in Kelvin, but I made them display in Celsius on my thing for sanity checking the dynamic terrain. Honestly it might be super useful for us to play some Elite: Dangerous and see the distances / temperatures of planets for different star classes.

**Comment by nstgeorge** [comment]
To really check this thoroughly, we could generate exactly the same system as one we find in E:D and see how the planets react.

**Comment by rvanasa** [comment]
Yeah that's a good idea! I also just figured out the problem—it's because the radii and densities are like two orders of magnitude less than they should be, making the luminosity absolutely insane. I'll also do some basic rebalancing in the next PR (such as adding a logarithmic temperature curve), and then we can both experiment with the distances and distributions over time.

**Comment by rvanasa** [comment]
Just found an outstanding reference page:

https://nssdc.gsfc.nasa.gov/planetary/factsheet/
